In [3]:
import numpy as np
load_data = np.load("new_liver_dataset.npz")
print(load_data.files)
print(load_data['images'].shape)
print(load_data['labels'].shape)

['images', 'labels']
(600, 64, 64, 3)
(600,)


In [6]:
arr = load_data['images']
print(arr.shape)
print(arr.dtype)
print(arr[0])

(600, 64, 64, 3)
uint8
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [7]:
load_data = np.load("new_processed_dataset.npz")
print(load_data.files)


['X_train', 'X_val', 'X_test', 'y_train', 'y_val', 'y_test']


In [10]:
images = load_data['X_train']
labels = load_data['y_train']
print(f"Image shape: {images[0].shape}")
print(f"Label shape: {labels[0].shape}")

Image shape: (64, 64, 3)
Label shape: ()


In [11]:
arr = load_data['X_train']
print("Array shape:", arr.shape)   
print("Array dtype:", arr.dtype)
print("First image data (flattened):", arr[0].flatten())

Array shape: (420, 64, 64, 3)
Array dtype: float32
First image data (flattened): [0. 0. 0. ... 0. 0. 0.]


In [1]:
import numpy as np
import pandas as pd

load_data = np.load("new_processed_dataset.npz")

x = np.concatenate([
    load_data["X_train"],
    load_data["X_val"],
    load_data["X_test"]
])
y = np.concatenate([
    load_data["y_train"],
    load_data["y_val"],
    load_data["y_test"]
])

x_flat= x.reshape(x.shape[0],-1)
df = pd.DataFrame(x_flat)
df["label"]=y

df.to_csv("processed_data.csv",index= False)
print("CSV saved")
print("shape:", df.shape)


CSV saved
shape: (600, 12289)
